all:
	javac *.java ast/*.java eval/*.java parser/*.java visitor/*.java eval/funcs/*.java eval/value/*.java

clean:
	rm *.class ast/*.class eval/*.class parser/*.class visitor/*.class eval/funcs/*.class eval/value/*.class
